###
POST http://localhost:3443/api/user
Content-Type: application/json

{
  "name": "Emir",
  "password": "securePassword123"
}

###
POST http://localhost:3443/api/login
Content-Type: application/json

{
  "name": "Emir",
  "password": "securePassword123"
}

###
POST http://localhost:3443/api/login
Content-Type: application/json

{
  "name": "JohnDoe",
  "password": "securePassword13"
}

###
DELETE http://localhost:3443/api/login
